/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as public401RouteImport } from './routes/(public)/401'
import { Route as protectedhomeRouteRouteImport } from './routes/(protected)/(home)/route'
import { Route as protectedUsersIndexRouteImport } from './routes/(protected)/users/index'
import { Route as protectedStoresIndexRouteImport } from './routes/(protected)/stores/index'
import { Route as protectedRolesIndexRouteImport } from './routes/(protected)/roles/index'
import { Route as protectedProfileIndexRouteImport } from './routes/(protected)/profile/index'
import { Route as protectedProductsIndexRouteImport } from './routes/(protected)/products/index'
import { Route as protectedhomeIndexRouteImport } from './routes/(protected)/(home)/index'
import { Route as protectedUsersStatisticsRouteImport } from './routes/(protected)/users/statistics'
import { Route as protectedUsersAdduserRouteImport } from './routes/(protected)/users/adduser'
import { Route as protectedStoresAddstoreRouteImport } from './routes/(protected)/stores/addstore'
import { Route as protectedRolesAddroleRouteImport } from './routes/(protected)/roles/addrole'
import { Route as protectedProductsAddproductRouteImport } from './routes/(protected)/products/addproduct'
import { Route as protectedhomeStatisticsusersRouteImport } from './routes/(protected)/(home)/statisticsusers'
import { Route as protectedhomeStatisticsproductsRouteImport } from './routes/(protected)/(home)/statisticsproducts'
import { Route as protectedhomeStatisticsStoresRouteImport } from './routes/(protected)/(home)/statisticsStores'
import { Route as protectedUsersEditIdRouteImport } from './routes/(protected)/users/edit/$id'
import { Route as protectedStoresStoreIdRouteImport } from './routes/(protected)/stores/store/$id'
import { Route as protectedStoresEditIdRouteImport } from './routes/(protected)/stores/edit/$id'
import { Route as protectedRolesEditIdRouteImport } from './routes/(protected)/roles/edit/$id'
import { Route as protectedProductsProductIdRouteImport } from './routes/(protected)/products/product/$id'
import { Route as protectedProductsEditIdRouteImport } from './routes/(protected)/products/edit/$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/(public)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const public401Route = public401RouteImport.update({
  id: '/(public)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedhomeRouteRoute = protectedhomeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUsersIndexRoute = protectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedStoresIndexRoute = protectedStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedRolesIndexRoute = protectedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedProfileIndexRoute = protectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedProductsIndexRoute = protectedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedhomeIndexRoute = protectedhomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedhomeRouteRoute,
} as any)
const protectedUsersStatisticsRoute =
  protectedUsersStatisticsRouteImport.update({
    id: '/users/statistics',
    path: '/users/statistics',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedUsersAdduserRoute = protectedUsersAdduserRouteImport.update({
  id: '/users/adduser',
  path: '/users/adduser',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedStoresAddstoreRoute = protectedStoresAddstoreRouteImport.update({
  id: '/stores/addstore',
  path: '/stores/addstore',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedRolesAddroleRoute = protectedRolesAddroleRouteImport.update({
  id: '/roles/addrole',
  path: '/roles/addrole',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedProductsAddproductRoute =
  protectedProductsAddproductRouteImport.update({
    id: '/products/addproduct',
    path: '/products/addproduct',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedhomeStatisticsusersRoute =
  protectedhomeStatisticsusersRouteImport.update({
    id: '/statisticsusers',
    path: '/statisticsusers',
    getParentRoute: () => protectedhomeRouteRoute,
  } as any)
const protectedhomeStatisticsproductsRoute =
  protectedhomeStatisticsproductsRouteImport.update({
    id: '/statisticsproducts',
    path: '/statisticsproducts',
    getParentRoute: () => protectedhomeRouteRoute,
  } as any)
const protectedhomeStatisticsStoresRoute =
  protectedhomeStatisticsStoresRouteImport.update({
    id: '/statisticsStores',
    path: '/statisticsStores',
    getParentRoute: () => protectedhomeRouteRoute,
  } as any)
const protectedUsersEditIdRoute = protectedUsersEditIdRouteImport.update({
  id: '/users/edit/$id',
  path: '/users/edit/$id',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedStoresStoreIdRoute = protectedStoresStoreIdRouteImport.update({
  id: '/stores/store/$id',
  path: '/stores/store/$id',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedStoresEditIdRoute = protectedStoresEditIdRouteImport.update({
  id: '/stores/edit/$id',
  path: '/stores/edit/$id',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedRolesEditIdRoute = protectedRolesEditIdRouteImport.update({
  id: '/roles/edit/$id',
  path: '/roles/edit/$id',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedProductsProductIdRoute =
  protectedProductsProductIdRouteImport.update({
    id: '/products/product/$id',
    path: '/products/product/$id',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedProductsEditIdRoute = protectedProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/401': typeof public401Route
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/statisticsStores': typeof protectedhomeStatisticsStoresRoute
  '/statisticsproducts': typeof protectedhomeStatisticsproductsRoute
  '/statisticsusers': typeof protectedhomeStatisticsusersRoute
  '/products/addproduct': typeof protectedProductsAddproductRoute
  '/roles/addrole': typeof protectedRolesAddroleRoute
  '/stores/addstore': typeof protectedStoresAddstoreRoute
  '/users/adduser': typeof protectedUsersAdduserRoute
  '/users/statistics': typeof protectedUsersStatisticsRoute
  '/': typeof protectedhomeIndexRoute
  '/products/': typeof protectedProductsIndexRoute
  '/profile/': typeof protectedProfileIndexRoute
  '/roles/': typeof protectedRolesIndexRoute
  '/stores/': typeof protectedStoresIndexRoute
  '/users/': typeof protectedUsersIndexRoute
  '/products/edit/$id': typeof protectedProductsEditIdRoute
  '/products/product/$id': typeof protectedProductsProductIdRoute
  '/roles/edit/$id': typeof protectedRolesEditIdRoute
  '/stores/edit/$id': typeof protectedStoresEditIdRoute
  '/stores/store/$id': typeof protectedStoresStoreIdRoute
  '/users/edit/$id': typeof protectedUsersEditIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/401': typeof public401Route
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/statisticsStores': typeof protectedhomeStatisticsStoresRoute
  '/statisticsproducts': typeof protectedhomeStatisticsproductsRoute
  '/statisticsusers': typeof protectedhomeStatisticsusersRoute
  '/products/addproduct': typeof protectedProductsAddproductRoute
  '/roles/addrole': typeof protectedRolesAddroleRoute
  '/stores/addstore': typeof protectedStoresAddstoreRoute
  '/users/adduser': typeof protectedUsersAdduserRoute
  '/users/statistics': typeof protectedUsersStatisticsRoute
  '/': typeof protectedhomeIndexRoute
  '/products': typeof protectedProductsIndexRoute
  '/profile': typeof protectedProfileIndexRoute
  '/roles': typeof protectedRolesIndexRoute
  '/stores': typeof protectedStoresIndexRoute
  '/users': typeof protectedUsersIndexRoute
  '/products/edit/$id': typeof protectedProductsEditIdRoute
  '/products/product/$id': typeof protectedProductsProductIdRoute
  '/roles/edit/$id': typeof protectedRolesEditIdRoute
  '/stores/edit/$id': typeof protectedStoresEditIdRoute
  '/stores/store/$id': typeof protectedStoresStoreIdRoute
  '/users/edit/$id': typeof protectedUsersEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(protected)/(home)': typeof protectedhomeRouteRouteWithChildren
  '/(public)/401': typeof public401Route
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRoute
  '/(protected)/(home)/statisticsStores': typeof protectedhomeStatisticsStoresRoute
  '/(protected)/(home)/statisticsproducts': typeof protectedhomeStatisticsproductsRoute
  '/(protected)/(home)/statisticsusers': typeof protectedhomeStatisticsusersRoute
  '/(protected)/products/addproduct': typeof protectedProductsAddproductRoute
  '/(protected)/roles/addrole': typeof protectedRolesAddroleRoute
  '/(protected)/stores/addstore': typeof protectedStoresAddstoreRoute
  '/(protected)/users/adduser': typeof protectedUsersAdduserRoute
  '/(protected)/users/statistics': typeof protectedUsersStatisticsRoute
  '/(protected)/(home)/': typeof protectedhomeIndexRoute
  '/(protected)/products/': typeof protectedProductsIndexRoute
  '/(protected)/profile/': typeof protectedProfileIndexRoute
  '/(protected)/roles/': typeof protectedRolesIndexRoute
  '/(protected)/stores/': typeof protectedStoresIndexRoute
  '/(protected)/users/': typeof protectedUsersIndexRoute
  '/(protected)/products/edit/$id': typeof protectedProductsEditIdRoute
  '/(protected)/products/product/$id': typeof protectedProductsProductIdRoute
  '/(protected)/roles/edit/$id': typeof protectedRolesEditIdRoute
  '/(protected)/stores/edit/$id': typeof protectedStoresEditIdRoute
  '/(protected)/stores/store/$id': typeof protectedStoresStoreIdRoute
  '/(protected)/users/edit/$id': typeof protectedUsersEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/401'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/statisticsStores'
    | '/statisticsproducts'
    | '/statisticsusers'
    | '/products/addproduct'
    | '/roles/addrole'
    | '/stores/addstore'
    | '/users/adduser'
    | '/users/statistics'
    | '/'
    | '/products/'
    | '/profile/'
    | '/roles/'
    | '/stores/'
    | '/users/'
    | '/products/edit/$id'
    | '/products/product/$id'
    | '/roles/edit/$id'
    | '/stores/edit/$id'
    | '/stores/store/$id'
    | '/users/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/401'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/statisticsStores'
    | '/statisticsproducts'
    | '/statisticsusers'
    | '/products/addproduct'
    | '/roles/addrole'
    | '/stores/addstore'
    | '/users/adduser'
    | '/users/statistics'
    | '/'
    | '/products'
    | '/profile'
    | '/roles'
    | '/stores'
    | '/users'
    | '/products/edit/$id'
    | '/products/product/$id'
    | '/roles/edit/$id'
    | '/stores/edit/$id'
    | '/stores/store/$id'
    | '/users/edit/$id'
  id:
    | '__root__'
    | '/(protected)'
    | '/$'
    | '/(protected)/(home)'
    | '/(public)/401'
    | '/(public)/forgot-password'
    | '/(public)/login'
    | '/(public)/register'
    | '/(protected)/(home)/statisticsStores'
    | '/(protected)/(home)/statisticsproducts'
    | '/(protected)/(home)/statisticsusers'
    | '/(protected)/products/addproduct'
    | '/(protected)/roles/addrole'
    | '/(protected)/stores/addstore'
    | '/(protected)/users/adduser'
    | '/(protected)/users/statistics'
    | '/(protected)/(home)/'
    | '/(protected)/products/'
    | '/(protected)/profile/'
    | '/(protected)/roles/'
    | '/(protected)/stores/'
    | '/(protected)/users/'
    | '/(protected)/products/edit/$id'
    | '/(protected)/products/product/$id'
    | '/(protected)/roles/edit/$id'
    | '/(protected)/stores/edit/$id'
    | '/(protected)/stores/store/$id'
    | '/(protected)/users/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  public401Route: typeof public401Route
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/401': {
      id: '/(public)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof public401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/(home)': {
      id: '/(protected)/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedhomeRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/users/': {
      id: '/(protected)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof protectedUsersIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/stores/': {
      id: '/(protected)/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof protectedStoresIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/roles/': {
      id: '/(protected)/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof protectedRolesIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/profile/': {
      id: '/(protected)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof protectedProfileIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/products/': {
      id: '/(protected)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof protectedProductsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(home)/': {
      id: '/(protected)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedhomeIndexRouteImport
      parentRoute: typeof protectedhomeRouteRoute
    }
    '/(protected)/users/statistics': {
      id: '/(protected)/users/statistics'
      path: '/users/statistics'
      fullPath: '/users/statistics'
      preLoaderRoute: typeof protectedUsersStatisticsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/users/adduser': {
      id: '/(protected)/users/adduser'
      path: '/users/adduser'
      fullPath: '/users/adduser'
      preLoaderRoute: typeof protectedUsersAdduserRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/stores/addstore': {
      id: '/(protected)/stores/addstore'
      path: '/stores/addstore'
      fullPath: '/stores/addstore'
      preLoaderRoute: typeof protectedStoresAddstoreRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/roles/addrole': {
      id: '/(protected)/roles/addrole'
      path: '/roles/addrole'
      fullPath: '/roles/addrole'
      preLoaderRoute: typeof protectedRolesAddroleRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/products/addproduct': {
      id: '/(protected)/products/addproduct'
      path: '/products/addproduct'
      fullPath: '/products/addproduct'
      preLoaderRoute: typeof protectedProductsAddproductRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(home)/statisticsusers': {
      id: '/(protected)/(home)/statisticsusers'
      path: '/statisticsusers'
      fullPath: '/statisticsusers'
      preLoaderRoute: typeof protectedhomeStatisticsusersRouteImport
      parentRoute: typeof protectedhomeRouteRoute
    }
    '/(protected)/(home)/statisticsproducts': {
      id: '/(protected)/(home)/statisticsproducts'
      path: '/statisticsproducts'
      fullPath: '/statisticsproducts'
      preLoaderRoute: typeof protectedhomeStatisticsproductsRouteImport
      parentRoute: typeof protectedhomeRouteRoute
    }
    '/(protected)/(home)/statisticsStores': {
      id: '/(protected)/(home)/statisticsStores'
      path: '/statisticsStores'
      fullPath: '/statisticsStores'
      preLoaderRoute: typeof protectedhomeStatisticsStoresRouteImport
      parentRoute: typeof protectedhomeRouteRoute
    }
    '/(protected)/users/edit/$id': {
      id: '/(protected)/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof protectedUsersEditIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/stores/store/$id': {
      id: '/(protected)/stores/store/$id'
      path: '/stores/store/$id'
      fullPath: '/stores/store/$id'
      preLoaderRoute: typeof protectedStoresStoreIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/stores/edit/$id': {
      id: '/(protected)/stores/edit/$id'
      path: '/stores/edit/$id'
      fullPath: '/stores/edit/$id'
      preLoaderRoute: typeof protectedStoresEditIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/roles/edit/$id': {
      id: '/(protected)/roles/edit/$id'
      path: '/roles/edit/$id'
      fullPath: '/roles/edit/$id'
      preLoaderRoute: typeof protectedRolesEditIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/products/product/$id': {
      id: '/(protected)/products/product/$id'
      path: '/products/product/$id'
      fullPath: '/products/product/$id'
      preLoaderRoute: typeof protectedProductsProductIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/products/edit/$id': {
      id: '/(protected)/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof protectedProductsEditIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedhomeRouteRouteChildren {
  protectedhomeStatisticsStoresRoute: typeof protectedhomeStatisticsStoresRoute
  protectedhomeStatisticsproductsRoute: typeof protectedhomeStatisticsproductsRoute
  protectedhomeStatisticsusersRoute: typeof protectedhomeStatisticsusersRoute
  protectedhomeIndexRoute: typeof protectedhomeIndexRoute
}

const protectedhomeRouteRouteChildren: protectedhomeRouteRouteChildren = {
  protectedhomeStatisticsStoresRoute: protectedhomeStatisticsStoresRoute,
  protectedhomeStatisticsproductsRoute: protectedhomeStatisticsproductsRoute,
  protectedhomeStatisticsusersRoute: protectedhomeStatisticsusersRoute,
  protectedhomeIndexRoute: protectedhomeIndexRoute,
}

const protectedhomeRouteRouteWithChildren =
  protectedhomeRouteRoute._addFileChildren(protectedhomeRouteRouteChildren)

interface protectedRouteRouteChildren {
  protectedhomeRouteRoute: typeof protectedhomeRouteRouteWithChildren
  protectedProductsAddproductRoute: typeof protectedProductsAddproductRoute
  protectedRolesAddroleRoute: typeof protectedRolesAddroleRoute
  protectedStoresAddstoreRoute: typeof protectedStoresAddstoreRoute
  protectedUsersAdduserRoute: typeof protectedUsersAdduserRoute
  protectedUsersStatisticsRoute: typeof protectedUsersStatisticsRoute
  protectedProductsIndexRoute: typeof protectedProductsIndexRoute
  protectedProfileIndexRoute: typeof protectedProfileIndexRoute
  protectedRolesIndexRoute: typeof protectedRolesIndexRoute
  protectedStoresIndexRoute: typeof protectedStoresIndexRoute
  protectedUsersIndexRoute: typeof protectedUsersIndexRoute
  protectedProductsEditIdRoute: typeof protectedProductsEditIdRoute
  protectedProductsProductIdRoute: typeof protectedProductsProductIdRoute
  protectedRolesEditIdRoute: typeof protectedRolesEditIdRoute
  protectedStoresEditIdRoute: typeof protectedStoresEditIdRoute
  protectedStoresStoreIdRoute: typeof protectedStoresStoreIdRoute
  protectedUsersEditIdRoute: typeof protectedUsersEditIdRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedhomeRouteRoute: protectedhomeRouteRouteWithChildren,
  protectedProductsAddproductRoute: protectedProductsAddproductRoute,
  protectedRolesAddroleRoute: protectedRolesAddroleRoute,
  protectedStoresAddstoreRoute: protectedStoresAddstoreRoute,
  protectedUsersAdduserRoute: protectedUsersAdduserRoute,
  protectedUsersStatisticsRoute: protectedUsersStatisticsRoute,
  protectedProductsIndexRoute: protectedProductsIndexRoute,
  protectedProfileIndexRoute: protectedProfileIndexRoute,
  protectedRolesIndexRoute: protectedRolesIndexRoute,
  protectedStoresIndexRoute: protectedStoresIndexRoute,
  protectedUsersIndexRoute: protectedUsersIndexRoute,
  protectedProductsEditIdRoute: protectedProductsEditIdRoute,
  protectedProductsProductIdRoute: protectedProductsProductIdRoute,
  protectedRolesEditIdRoute: protectedRolesEditIdRoute,
  protectedStoresEditIdRoute: protectedStoresEditIdRoute,
  protectedStoresStoreIdRoute: protectedStoresStoreIdRoute,
  protectedUsersEditIdRoute: protectedUsersEditIdRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  public401Route: public401Route,
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
